#ifndef YOLAH_FEATURES_H
#define YOLAH_FEATURES_H
#include "game.h"
#include <cstdint>

namespace YolahFeatures {
  enum {
    NO_MOVE_BLACK,
    MOVE_BLACK,
    CONNECTIVITY_BLACK,
    CONNECTIVITY_SET_BLACK,
    ALONE_BLACK,
    FIRST_BLACK,
    INFLUENCE_BLACK,
    BLOCKED_BLACK,
    FREEDOM_LOW_BLACK,
    FREEDOM_MID_BLACK,
    FREEDOM_HIGH_BLACK,
    GROUP_BLACK,
    CENTER_BLACK,
    LOWER_LEFT_CORNER_BLACK,
    LOWER_RIGHT_CORNER_BLACK,
    UPPER_RIGHT_CORNER_BLACK,
    UPPER_LEFT_CORNER_BLACK,
    LOWER_MIDDLE_BLACK,
    RIGHT_MIDDLE_BLACK,
    UPPER_MIDDLE_BLACK,
    LEFT_MIDDLE_BLACK,
	NO_MOVE_WHITE,
    MOVE_WHITE,
    CONNECTIVITY_WHITE,
    CONNECTIVITY_SET_WHITE,
    ALONE_WHITE,
    FIRST_WHITE,
    INFLUENCE_WHITE,
    BLOCKED_WHITE,
    FREEDOM_LOW_WHITE,
    FREEDOM_MID_WHITE,
    FREEDOM_HIGH_WHITE,
    GROUP_WHITE,
    CENTER_WHITE,
    LOWER_LEFT_CORNER_WHITE,
    LOWER_RIGHT_CORNER_WHITE,
    UPPER_RIGHT_CORNER_WHITE,
    UPPER_LEFT_CORNER_WHITE,
    LOWER_MIDDLE_WHITE,
    RIGHT_MIDDLE_WHITE,
    UPPER_MIDDLE_WHITE,
    LEFT_MIDDLE_WHITE,    
    FREE,
    TURN,
    NB_FEATURES
  };
  void set_features(uint8_t* features, const Yolah &);
  void encode_data(const std::string& src_dir, const std::string& dst_dir);
}

#endif
