This is makeindex, version 2.15 [TeX Live 2022/dev] (kpathsea + Thai support).
Scanning style file ./book.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file book.acn....done (7 entries accepted, 0 rejected).
Sorting entries....done (20 comparisons).
Generating output file book.acr....done (10 lines written, 0 warnings).
Output written in book.acr.
Transcript written in book.alg.
